### ISSUE TITLE
!modules command doesn't appear to work

### ISSUE THREAD

**Issue by rexkix** [samfundev/KtaneTwitchPlays#272]
For some reason, the !modules command doesn't appear to work.
It feels as if this happened just as the automatic camera wall was added.  Maybe it has something to do with that?

**Comment by red031000** [comment]
this was removed intentionally, it might be worth adding it back in, if there's still demand for it to be used

**Comment by rexkix** [comment]
Why was it removed?  I've seen cases where people do a !uncv to unclaim a module and I don't know the number of the module that was unclaimed.  I want to view the remaining few modules by using the !module command.

**Comment by samfundev** [comment]
I don't think there's demand for this command to return, so I'm going to close this.
