### ISSUE TITLE
Make it so modules that pop up to the side view prefer to replace unclaimed modules

### ISSUE THREAD

**Issue by rexkix** [samfundev/KtaneTwitchPlays#273]
A lot of the time when a module is !viewed (or whatever) and is put in a side view it replaces a module that is claimed when there are other modules in the side-view that are unclaimed.  Please make it prefer to replace a module that is unclaimed first.

**Comment by rexkix** [comment]
This is especially a problem when going from auto-camera wall to non-camera wall.  It seems to trigger when there are only 6 modules claimed, but it puts a bunch of unclaimed modules into the view.  This doesn't help when you've claimed one of the modules that doesn't get the view.

**Comment by rexkix** [comment]
This is hard to verify:
1. Now that camera wall stays enabled until only 4 modules remain unsolved, this doesn't happen as often.
2. I'm not doing TP as much as I used to.

I keep looking for somebody else to test and I don't see any of my friends online doing TP when I've checked.  I don't know if you want to close this or wait until I can test further.

**Comment by samfun123** [comment]
Let me know when you've tested it further.

**Comment by samfundev** [comment]
Closed due to lack of activity.
