### ISSUE TITLE
Re-Implement ClaimCooldownTime

### ISSUE THREAD

**Issue by red031000** [samfundev/KtaneTwitchPlays#282]
During the bugfixes of the command re-write, ClaimCooldownTime was removed to fix a bug, since it's no-longer buggy, consider re-implementing ClaimCooldownTime, or removing it altogether

**Comment by CaitSith2** [comment]
Factory mode Finite/Infinite mode bombs not working after the first bomb.

**Comment by PeterRed4091** [comment]
Since the context of this issue has changed, consider dropping the "bug" label and adding the "enhancement" label.

**Comment by samfun123** [comment]
I still consider this to be a bug since it's a regression. I still think we should just remove this feature because no one has been asking for it back.

**Comment by samfundev** [comment]
Since this hasn't been requested, I'm removed this setting.
