### ISSUE TITLE
module claim conflict

### ISSUE THREAD

**Issue by red031000** [samfundev/KtaneTwitchPlays#289]
a module (the digit) was claimed as there was a command in the queue, this command got a strike, and instead of striking the person who issued the command, TP issued a strike to the person who claimed the module

**Comment by uku1928** [comment]
yield return strike moment (also this was all the way back in 2018, is this fixed now?)

**Comment by samfundev** [comment]
[This has been fixed in the module.](https://github.com/marksam32/ktaneTheDigit/commit/3096bc2a459da39769d34f8c9e47519be2230bee)
