### ISSUE TITLE
Make a new command addbonus <points> [<solves> [<strikes>]]

### ISSUE THREAD

**Issue by rexkix** [samfundev/KtaneTwitchPlays#312]
Oops.  Empty description.  Let's see if we can fix this.

A lot of the time, people want to correct a situation where a solve went to the wrong person or a strike was caused inappropriately.  It would be nice not to have to do 3 separate "addbonuspoints", "add bonussolves", "addbonusstrikes" commands.  Sometimes you want to give one guy credit and the other guy "anti-credit" and this makes for 6 commands.  What a hassle.

**Comment by samfundev** [comment]
We have `!srefund` and `!stransfer` which I think covers this.
