### ISSUE TITLE
Restart and Update command issues

### ISSUE THREAD

**Issue by MrPeanut1028** [samfundev/KtaneTwitchPlays#491]
When you do either `!update` or `!restart` the game will not always start back up, likely due to a Steam Workshop update. This may be a known problem, but it should be fixed if at all possible.

**Comment by MrPeanut1028** [comment]
Yes, but it isn't always possible (ex. Strike's stream was stuck at `!binder drop` but commands like `!help` were still going thorough. `!stop` did not work, likely because it wasn't in a bomb. The stream is now stuck with a blank non-game screen since I did `!restart`, as it was the last possible option. If I am able to recreate it, I can formally report the issue with `!binder drop`)

**Comment by samfun123** [comment]
@MrPeanut1028 For future reference, I'd recommend using the `!skip` command. It's a SuperUser command that skips the currently running coroutine if it gets stuck.

**Comment by MrPeanut1028** [comment]
Ah, thank you. I will definitely use that next time.

**Comment by samfun123** [comment]
I'd really appreciate some help with this issue as I don't know any way I could get Steam to launch the game without it also triggering a workshop update. If anyone has an idea, let me know.
