### ISSUE TITLE
No Full List of Commands

### ISSUE THREAD

**Issue by Kikithecat12345** [samfundev/KtaneTwitchPlays#494]
There is no comprehensive list of TP commands anywhere. Could someone update the wiki with more updated commands?

**Comment by samfun123** [comment]
The recommended list of TP commands is here: https://samfun123.github.io/KtaneTwitchPlays/ It's not comprehensive yet but I've been the only one who has been working on documenting commands. If anyone wants to help, just let me know and I explain how to.
I still need to make sure everything from the wiki has been moved to the new documentation but I'll at least put up that this is the recommended place to look.

**Comment by Kikithecat12345** [comment]
@samfun123 that documentation is great so far. Could you consider adding other bits of info such as configuration options, modes, (like what they do) etc?

**Comment by samfun123** [comment]
I think I want to keep that documentation for the players of TP. So modes could go on there but stuff for streamers is probably better on the wiki.

**Comment by samfundev** [comment]
Since pretty much every command has been documented now, I'm going to close this.
