### ISSUE TITLE
Some more scoring types

### ISSUE THREAD

**Issue by sleepin-fang** [samfundev/KtaneTwitchPlays#515]
2 types of scoring could be added:-
- Time based scoring that is for regular instead of only needy (e.g. T 0.02/s).
- Reward increase upon solved (Regular, Needy) e.g. (R S 3x). 

As well as linking them to the sheet, so it's configurable.

**Comment by samfun123** [comment]
I'd be willing to add these as long as we have a module that these would be used for.

**Comment by MrPeanut1028** [comment]
I know that the Time-based regular module scoring could be used for Random Access Memory and Ultimate Custom Night. Reward increases can be used for Art Appreciation, Mystery Module, and a couple of others that already handle this internally (Organization and TTKS come to mind).

**Comment by samfundev** [comment]
This should now be implemented.
